pipeline {
    agent any

    environment {
        GITHUB_REPOSITORY = "https://github.com/byoungjuchae/cover-agent.git"
    }

    stages {
        stage("Clone") {
            steps {
                sh 'git clone $GITHUB_REPOSITORY'
            }
        }
    }
}
