pipeline{
    agent any
    environment{
        github_respository = "https://github.com/byoungjuchae/cover-agent.git"
    }

    stage("Clone"){
            sh 'git clone $github_respository'
        }
    
}