pipeline {
    agent any

    environment {
        GITHUB_REPOSITORY = "https://github.com/byoungjuchae/cover-agent.git"
        GIT_BRANCH = "main"
        DOCKER_IMAGE_NAME = "cover_letter"
        DOCKER_TAG = "0.1v"
    }

    stages {
        stage("Clone") {
            steps {
                checkout([$class: 'GitSCM',
                    branches: [[name: "*/${env.GIT_BRANCH}"]],
                    userRemoteConfigs: [[
                        url: "${env.GITHUB_REPOSITORY}"
                    ]]])
            }
        }
        stage("Docker"){
            steps{
                script {
                    docker.build(DOCKER_IMAGE_NAME+":"+DOCKER_TAG)
                    sh "docker build -t ${DOCKER_IMAGE_NAME}:${DOCKER_TAG} ."
                }
            }
        }

    }
}
